<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PhotoCleanerBenchmarks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="CliWrap" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PhotoCleaner/PhotoCleaner.csproj" />
  </ItemGroup>
</Project>
