<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PhotoCleanerBenchmarks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="CliWrap" Version="3.10.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PhotoCleaner/PhotoCleaner.csproj" />
  </ItemGroup>
</Project>
